### ISSUE TITLE
"Not a valid package for AnkiDroid"

### ISSUE THREAD

**Issue by ChrisJayX10** [infinyte7/ankidroid-js-addon#1]
Unfortunately it doesn't work for me. I have a Samsung Galaxy S10e, I downloaded the 1.01 version of AnkiDroid JS for my cpu architecture (arm64-v8a) and installed it with Package installer. No matter which addon I try to install (even the "valid" test addon) I get a message saying "Not a valid package for AnkiDroid".

I was really hoping that I could get a progress bar in my AnkiDroid this way, I'm really disappointed it didn't work out in the end :(

**Comment by krmanik** [comment]
The AnkiDroid.JS version is updated now. It will work now.
**View installation instructions [here](https://github.com/infinyte7/ankidroid-js-addon#how-to-install-addons)**

<img src="https://github.com/infinyte7/ankidroid-js-addon/blob/main/images/progress_bar_addon.gif?raw=true" height=450px></img>

**Comment by ChrisJayX10** [comment]
That's great it works now, thanks so much!
